"""Alias update in devices

Revision ID: ce0bda32d44b
Revises: 454e266dbdca
Create Date: 2020-05-07 14:45:53.201950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0bda32d44b'
down_revision = '454e266dbdca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('alias', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'alias')
    # ### end Alembic commands ###
