"""Removed Alias and made

Revision ID: 6a5752cdd96a
Revises: ce0bda32d44b
Create Date: 2020-05-08 16:39:39.384423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5752cdd96a'
down_revision = 'ce0bda32d44b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'alias')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('alias', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
